### ISSUE TITLE
EPIC: refactor v2

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/toshi-hazard-post#26]
A ground-up rewrite of `toshi-hazard-post` is wanted due to:
- changes in how realizations are accessed via `toshi-hazad-store`
- changes to how sources are defined for component branches in `runzi` and `nzshm-model`
- changes to how logic trees are stored/defined in `nzhsm-model`
- changes to the logic tree classes in `nzhsm-model`

## Steps
All steps require test coverage
- [x] #25 
- [x] implement calculation of weights
- [x] implement calculation of composite rates
- [x] #28
- [x] #29
- [x] mock use `toshi-hazard-store` v2 to retrieve component probabilities
- [x] implement calculation of aggregate rates
- [x] use `toshi-hazard-store` v2 to retrieve component probabilities
- [x] save results with `toshi-hazard-store`
- [x] add logging
- [x] add script
